## **A Pythonic Neuron**

In [ ]:
import numpy as np

In [ ]:
example_input = [1, .2, .1, .05, .2]

In [ ]:
example_weights = [.2, .12, .4, .6, .90]

In [ ]:
input_vector = np.array(example_input)

In [ ]:
weights = np.array(example_weights)

In [ ]:
bias_weight = .2

In [ ]:
activation_level = np.dot(input_vector, weights) + (bias_weight * 1)

In [ ]:
activation_level

0.6740000000000002

In [ ]:
threshold = .5

In [ ]:
if activation_level >= threshold:
  perceptron_output = 1
else:
  perceptron_output = 0

In [ ]:
perceptron_output

1

In [ ]:
expected_output = 0

In [ ]:
new_weights = []

In [ ]:
for i, x in enumerate(example_input):
  new_weights.append(weights[i] + (expected_output - perceptron_output) * x)

weights = np.array(new_weights)

In [ ]:
example_weights

[0.2, 0.12, 0.4, 0.6, 0.9]

In [ ]:
weights

array([-0.8 , -0.08,  0.3 ,  0.55,  0.7 ])

In [ ]:
sample_data = [[0, 0], [0, 1], [1, 0], [1, 1]]

In [ ]:
expected_results = [0, 1, 1, 1]

In [ ]:
activation_threshold = 0.5

In [ ]:
from random import random

In [ ]:
import numpy

In [ ]:
weights = np.random.random(2)/1000 # Small random float 0 < w < 00.1

In [ ]:
weights

array([0.00030694, 0.00020861])

In [ ]:
for idx, sample in enumerate(sample_data):
  input_vector = np.array(sample)
  activation_level = np.dot(input_vector, weights) + (bias_weight * 1)
  if activation_level > activation_threshold:
    perceptron_output = 1
  else:
    perceptron_output = 0

  print('Predicted {}'.format(perceptron_output))
  print('Expected: {}'.format(expected_results[idx]))

Predicted 0
Expected: 0
Predicted 0
Expected: 1
Predicted 0
Expected: 1
Predicted 0
Expected: 1


In [ ]:
for idx, sample in enumerate(sample_data):
  input_vector = np.array(sample)
  print(input_vector, weights)

[0 0] [0.00030694 0.00020861]
[0 1] [0.00030694 0.00020861]
[1 0] [0.00030694 0.00020861]
[1 1] [0.00030694 0.00020861]


In [ ]:
input_vector

array([1, 1])

In [ ]:
bias_weight

0.2

In [ ]:
np.dot([0, 1], [0.00085712, 0.0003444])

0.0003444

In [ ]:
for iteration_num in range(5):
  correct_answers = 0
  for idx, sample in enumerate(sample_data):
    input_vector = np.array(sample)
    weights = np.array(weights)
    activation_level = np.dot(input_vector, weights) + (bias_weight * 1)
    if activation_level > activation_threshold:
      perceptron_output = 1
    else:
      perceptron_output = 0
    if perceptron_output == expected_results[idx]:
      correct_answers = correct_answers + 1
    new_weights = []
    for i, x in enumerate(sample):
      print(weights[i], expected_results[idx], perceptron_output)
      new_weights.append(weights[i] + (expected_results[idx] - perceptron_output) * x)
    print(bias_weight, expected_results[idx], perceptron_output)
    bias_weight = bias_weight + ((expected_results[idx] - perceptron_output) * 1)
    weights = np.array(new_weights)
  print('{} correct answers out of 4, for iteration {}'.format(correct_answers, iteration_num))


0.00030694178289667905 0 0
0.00020861374579035597 0 0
0.2 0 0
0.00030694178289667905 1 0
0.00020861374579035597 1 0
0.2 1 0
0.00030694178289667905 1 1
1.0002086137457904 1 1
1.2 1 1
0.00030694178289667905 1 1
1.0002086137457904 1 1
1.2 1 1
3 correct answers out of 4, for iteration 0
0.00030694178289667905 0 1
1.0002086137457904 0 1
1.2 0 1
0.00030694178289667905 1 1
1.0002086137457904 1 1
0.19999999999999996 1 1
0.00030694178289667905 1 0
1.0002086137457904 1 0
0.19999999999999996 1 0
1.0003069417828967 1 1
1.0002086137457904 1 1
1.2 1 1
2 correct answers out of 4, for iteration 1
1.0003069417828967 0 1
1.0002086137457904 0 1
1.2 0 1
1.0003069417828967 1 1
1.0002086137457904 1 1
0.19999999999999996 1 1
1.0003069417828967 1 1
1.0002086137457904 1 1
0.19999999999999996 1 1
1.0003069417828967 1 1
1.0002086137457904 1 1
0.19999999999999996 1 1
3 correct answers out of 4, for iteration 2
1.0003069417828967 0 0
1.0002086137457904 0 0
0.19999999999999996 0 0
1.0003069417828967 1 1
1.000208613

# **Keras Implementation**

In [ ]:
import numpy as np

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [ ]:
# Our examples for an exclusive XOR
x_train = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_train = np.array([[0], [1], [1], [0]])
model = Sequential()
num_neurons = 10
model.add(Dense(num_neurons, input_dim=2))
model.add(Activation('tanh'))
model.add(Dense(1))
model.add(Activation('sigmoid'))
model.summary()


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 10)                30        
_________________________________________________________________
activation_2 (Activation)    (None, 10)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
_________________________________________________________________
activation_3 (Activation)    (None, 1)                 0         
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [ ]:
sgd = SGD(lr=0.1)
model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])

In [ ]:
model.predict(x_train)

array([[0.5       ],
       [0.55117387],
       [0.44584534],
       [0.5047216 ]], dtype=float32)

In [ ]:
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6998 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6993 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 941us/step - loss: 0.6989 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6984 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6980 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6975 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6971 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6966 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6962 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6957 - accuracy: 0.5000
Epoch 11/100
1/1 [=========

In [ ]:
model.predict(x_train)

array([[0.46156928],
       [0.54988927],
       [0.49556398],
       [0.5138205 ]], dtype=float32)

In [ ]:
import h5py
model_structure = model.to_json()


In [ ]:
with open("basic_model.json", "w") as json_file:
  json_file.write(model_structure)

In [ ]:
model.save_weights("basic_weights.h5")
print("Model saved.")

Model saved.


In [ ]:
print(model.predict_classes(x_train))
print(model.predict(x_train))

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
[[0]
 [1]
 [0]
 [1]]
[[0.46156928]
 [0.54988927]
 [0.49556398]
 [0.5138205 ]]
